### ISSUE TITLE
keys is undefined?

### ISSUE THREAD

**Issue by beernutz** [b0o/surfingkeys-conf#1]
Hey, i would really like to use your config as it exists, but it gives an error when trying to "save" it in the editor:
**Reference error: keys is not defined.**

Just reading over the script i don't see a place where that would be true, but i am not as familiar with editing in surfingkeys's vim editor.

Please advise

**Comment by b0o** [comment]
Hey @beernutz, please see the [README installation instructions](https://github.com/b0o/surfingkeys-conf#installation).

If you'd like to use the configuration by just copying and pasting, you can manually paste the contents of [conf.priv.example.js](https://github.com/b0o/surfingkeys-conf/blob/master/conf.priv.example.js) before the contents [conf.js](https://github.com/b0o/surfingkeys-conf/blob/master/conf.js) directly in the SurfingKeys configuration box. This isn't the recommended way to install, but it should mostly work.

The `keys` object contains API keys for use with several of the third party APIs included with this configuration (Crunchbase, Domainr, YouTube, WolframAlpha, Elixir Google Custom Search). You'll need to follow the instructions in the README in order for those select few to fully work, because you need to obtain your own personal API keys from those providers. Everything else should work, though.

**Comment by beernutz** [comment]
Holy smokes, I am sorry I did NOT read the darn README!  Ish.  Sorry for bothering you with this.

R.T.F.README.  lol
